import Navigation from '@/components/Navigation'
import Wrapper from '@/components/Wrapper'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>The Movie App</title>
        <meta name="description" content="Movie App, generated by NextJS & TheMovieDB" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navigation />
        <Wrapper />
      </div>
    </>
  )
}
